test: updating publish stage as reference from Solnlib repo.

diff --git a/.github/workflows/build-test-release.yml b/.github/workflows/build-test-release.yml
--- a/.github/workflows/build-test-release.yml
+++ b/.github/workflows/build-test-release.yml
@@ -150,7 +150,7 @@ jobs:
         with:
           scanArguments: "--max_dept 50 -x .github/workflows/exclude-patterns.txt"
   publish:
-    if: github.event_name != 'pull_request'
+    if: always()
     needs:
       - pre-commit
       - semgrep
@@ -158,7 +158,26 @@ jobs:
       - build
       - review_secrets
     runs-on: ubuntu-latest
+    env:
+      NEEDS: ${{ toJson(needs) }}
     steps:
+      - name: check if tests have passed or skipped
+        if: github.event_name != 'pull_request'
+        id: check
+        shell: bash
+        run: |
+          RUN_PUBLISH=$(echo "$NEEDS" | jq ".[] |  select(  ( .result != \"skipped\" ) and .result != \"success\" ) | length == 0")
+          if [[ $RUN_PUBLISH != *'false'* ]]
+          then
+              echo "::set-output name=run-publish::true"
+          else
+              echo "::set-output name=run-publish::false"
+          fi
+      - name: exit without publish
+        if: ${{ steps.check.outputs.run-publish == 'false' || github.event_name == 'pull_request'}}
+        run: |
+          echo " some test job failed. "
+          exit 1
       - name: Checkout
         uses: actions/checkout@v2
         with:
